- hosts: node01
  remote_user: root
  tasks:
    - name: install nginx
      yum: 
        name=nginx
        state=installed
    - name: start nginx
      service:
        name=nginx
        state:started
    - name: check
      command: ss -tnulp
    
